import { useEffect, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, Banknote, Download, Flag, Landmark, Loader2, MessageCircle, ShieldAlert, SlidersHorizontal, UsersRound, X } from "lucide-react";
import { toast } from "sonner";
import { OfficialServiceReceipt } from "./OfficialServiceReceipt";
import "./launch-refinements.css";

const formatXaf = (value: number) => `${new Intl.NumberFormat("en-US").format(value)} XAF`;
const csvCell = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`;
type SettingsDraft = {
  agentAccessFeeXaf: number;
  starterAccessFeeXaf: number;
  proAccessFeeXaf: number;
  featuredPinFeeXaf: number;
  routeBatchVerificationFeeXaf: number;
  physicalVerificationFeeXaf: number;
  fieldModeratorShareBps: number;
  ownerAlertsEnabled: boolean;
};

export default function AdminPortal({ onClose }: { onClose: () => void }) {
  const { user, isAuthenticated } = useAuth();
  const enabled = isAuthenticated && user?.role === "admin";
  const utils = trpc.useUtils();
  const settings = trpc.admin.settings.useQuery(undefined, { enabled });
  const users = trpc.admin.users.useQuery(undefined, { enabled });
  const cashFlow = trpc.admin.cashFlowAudit.useQuery(undefined, { enabled });
  const payments = trpc.admin.paymentQueue.useQuery(undefined, { enabled });
  const [receiptOrderId, setReceiptOrderId] = useState<string | null>(null);
  const receipt = trpc.admin.officialServiceReceipt.useQuery({ orderId: receiptOrderId ?? "" }, { enabled: enabled && Boolean(receiptOrderId) });
  const commissionLedger = trpc.admin.commissionLedger.useQuery(undefined, { enabled });
  const verificationAudits = trpc.admin.verificationAudits.useQuery(undefined, { enabled });
  const trustReports = trpc.admin.trustReports.useQuery(undefined, { enabled });
  const leadEvents = trpc.admin.leadEvents.useQuery(undefined, { enabled });
  const ownerAlertProvider = trpc.admin.ownerAlertProvider.useQuery(undefined, { enabled });
  const ownerAlerts = trpc.admin.ownerAlerts.useQuery({ limit: 40 }, { enabled });
  const [draft, setDraft] = useState<SettingsDraft | null>(null);
  const [reasons, setReasons] = useState<Record<number, string>>({});
  const [roleDrafts, setRoleDrafts] = useState<Record<number, "user" | "moderator" | "admin">>({});
  const [commissionReviewNotes, setCommissionReviewNotes] = useState<Record<number, string>>({});
  const [paymentNotes, setPaymentNotes] = useState<Record<string, string>>({});
  const [safetyReleaseReasons, setSafetyReleaseReasons] = useState<Record<string, string>>({});
  useEffect(() => {
    if (settings.data) setDraft({ agentAccessFeeXaf: settings.data.agentAccessFeeXaf, starterAccessFeeXaf: settings.data.starterAccessFeeXaf, proAccessFeeXaf: settings.data.proAccessFeeXaf, featuredPinFeeXaf: settings.data.featuredPinFeeXaf, routeBatchVerificationFeeXaf: settings.data.routeBatchVerificationFeeXaf, physicalVerificationFeeXaf: settings.data.physicalVerificationFeeXaf, fieldModeratorShareBps: settings.data.fieldModeratorShareBps, ownerAlertsEnabled: settings.data.ownerAlertsEnabled });
  }, [settings.data]);
  const updateSettings = trpc.admin.updateSettings.useMutation({ onSuccess: () => { utils.admin.settings.invalidate(); toast.success("Commercial settings saved and audited."); }, onError: error => toast.error(error.message) });
  const setBan = trpc.admin.setUserBan.useMutation({ onSuccess: () => { utils.admin.users.invalidate(); toast.success("Account access record updated."); }, onError: error => toast.error(error.message) });
  const setRole = trpc.admin.setUserRole.useMutation({ onSuccess: () => { utils.admin.users.invalidate(); toast.success("Trusted role assignment saved and audited."); }, onError: error => toast.error(error.message) });
  const approveHeldCommission = trpc.admin.approveHeldCommission.useMutation({ onSuccess: () => { utils.admin.commissionLedger.invalidate(); utils.admin.verificationAudits.invalidate(); utils.admin.cashFlowAudit.invalidate(); toast.success("Evidence review recorded. This commission is now payable."); }, onError: error => toast.error(error.message) });
  const reconcilePayment = trpc.admin.reconcilePayment.useMutation({ onSuccess: (result, variables) => { utils.admin.paymentQueue.invalidate(); utils.admin.cashFlowAudit.invalidate(); if (result.status === "confirmed") { setReceiptOrderId(variables.orderId); toast.success("Confirmed. Official AHC service receipt is ready to print."); } else toast.success("Official service-order reconciliation recorded."); }, onError: error => toast.error(error.message) });
  const sendOwnerAlertTest = trpc.admin.sendOwnerAlertTest.useMutation({ onSuccess: () => { utils.admin.ownerAlerts.invalidate(); toast.success("Owner-alert test was recorded. Check delivery status in the history below."); }, onError: error => toast.error(error.message) });
  const releaseSafetyHold = trpc.admin.releaseSafetyHold.useMutation({ onSuccess: () => { utils.admin.trustReports.invalidate(); utils.admin.ownerAlerts.invalidate(); toast.success("Safety hold released, reports resolved, and owner alert queued."); }, onError: error => toast.error(error.message) });
  const setNumber = (key: keyof SettingsDraft, raw: string) => setDraft(current => current ? { ...current, [key]: Number(raw) || 0 } : current);
  const paymentNote = (orderId: string) => paymentNotes[orderId] ?? "";
  const exportLedger = () => { const rows = commissionLedger.data ?? []; const csv = [["verification_order_id","listing_id","moderator","gross_xaf","moderator_xaf","platform_xaf","moderator_share_percent","status","recorded_at"], ...rows.map(x => [x.verificationOrderId,x.listingId,x.moderatorName ?? `Moderator #${x.moderatorUserId}`,x.grossAmountXaf,x.fieldModeratorAmountXaf,x.platformAmountXaf,(x.fieldModeratorShareBps / 100).toFixed(0),x.status,new Date(x.createdAt).toISOString()])].map(row => row.map(csvCell).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "ahc-verification-commission-ledger.csv"; link.click(); URL.revokeObjectURL(url); toast.success("Commission ledger CSV downloaded."); };

  if (!enabled) return <section className="agent-drawer admin-drawer"><button className="drawer-close" onClick={onClose}><X size={19} /></button><span className="section-overline">AHC / Admin</span><h2>Platform management is restricted.</h2><p>Only the designated AHC administrator can manage platform fees, cash-flow records, and account access. Field Moderators use <a href="#/operations">Operations</a> for on-ground review work.</p></section>;

  return <section className="agent-drawer scroll operations-drawer admin-drawer"><button className="drawer-close" onClick={onClose}><X size={19} /></button><header className="ops-atlas-header admin-atlas-header"><div className="ops-brand-lockup"><span className="ops-brand-emblem"><span /><span /><span /></span><span>Affordable Housing<b>Cameroon / platform admin</b></span></div><span className="section-overline">Admin route / restricted governance</span><h2>Manage trust, access, and the cash record.</h2><p>Field Moderators verify properties on the ground. Administrators set commercial rules, protect the network, and audit all paid activity.</p><span className="ops-trust-pulse"><i /> Admin audit on</span><a className="text-button" href="#/acceptance">Open the owner acceptance walkthrough →</a></header>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">01</span><h3><SlidersHorizontal size={18} /> Commercial settings</h3></div><div className="ops-status-strip"><span>Governed pricing</span><b>Changes apply to newly created payment orders only.</b></div>{!draft ? <p>Loading commercial settings…</p> : <form className="admin-settings-grid" onSubmit={event => { event.preventDefault(); updateSettings.mutate(draft); }}><label>New-Agent Welcome Bundle <span>XAF / first 30 days · five credits</span><input type="number" min="0" value={draft.agentAccessFeeXaf} onChange={event => setNumber("agentAccessFeeXaf", event.target.value)} /></label><label>Starter Access <span>XAF / 30 days · five credits</span><input type="number" min="0" value={draft.starterAccessFeeXaf} onChange={event => setNumber("starterAccessFeeXaf", event.target.value)} /></label><label>Pro Access <span>XAF / 30 days · priority / 20 active listings</span><input type="number" min="0" value={draft.proAccessFeeXaf} onChange={event => setNumber("proAccessFeeXaf", event.target.value)} /></label><label>Featured Landmark Pin <span>XAF / 7 days</span><input type="number" min="0" value={draft.featuredPinFeeXaf} onChange={event => setNumber("featuredPinFeeXaf", event.target.value)} /></label><label>Route-batch physical verification <span>XAF / route batch</span><input type="number" min="0" value={draft.routeBatchVerificationFeeXaf} onChange={event => setNumber("routeBatchVerificationFeeXaf", event.target.value)} /></label><label>Individual physical verification <span>XAF / individual visit</span><input type="number" min="0" value={draft.physicalVerificationFeeXaf} onChange={event => setNumber("physicalVerificationFeeXaf", event.target.value)} /></label><label>Field Moderator share <span>basis points / 10,000</span><input type="number" min="0" max="10000" value={draft.fieldModeratorShareBps} onChange={event => setNumber("fieldModeratorShareBps", event.target.value)} /></label><div className="admin-settings-callout"><b>{(draft.fieldModeratorShareBps / 100).toFixed(0)}% Field Moderator / {((10_000 - draft.fieldModeratorShareBps) / 100).toFixed(0)}% AHC</b><span>At the approved 80/20 split, route-batch verification is 4,000 XAF / 1,000 XAF and individual verification is 6,000 XAF / 1,500 XAF.</span></div><button className="button-primary" type="submit" disabled={updateSettings.isPending}>Save governed settings</button></form>}</section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">02</span><h3><Banknote size={18} /> Official service-order reconciliation</h3><span className="ops-count">{payments.data?.length ?? 0}</span></div><div className="ops-status-strip"><span>Admin finance control</span><b>Only platform-service orders appear here; AHC never reconciles rent, deposits, or tenancy settlements.</b></div>{payments.isLoading ? <p>Loading submitted service-order references…</p> : !payments.data?.length ? <p className="muted">No submitted service-order references are waiting for Admin review.</p> : <div className="ops-card-list">{payments.data.map(order => <article key={order.id} className="ops-card"><div className="ops-card-head"><div><span>{order.id}</span><h4>{order.agentName ?? "Unprofiled agent"} · {order.type.replaceAll("_", " ")}</h4></div><b>{formatXaf(order.amountXaf)}</b></div><p>{order.provider.replaceAll("_", " ")} reference: <code>{order.providerReference}</code></p><textarea value={paymentNote(order.id)} onChange={event => setPaymentNotes(current => ({ ...current, [order.id]: event.target.value }))} placeholder="Merchant receipt evidence or rejection reason" /><div className="ops-actions"><button className="button-secondary" disabled={reconcilePayment.isPending || paymentNote(order.id).trim().length < 6} onClick={() => reconcilePayment.mutate({ orderId: order.id, decision: "rejected", note: paymentNote(order.id) })}>Reject reference</button><button className="button-primary" disabled={reconcilePayment.isPending || paymentNote(order.id).trim().length < 6} onClick={() => reconcilePayment.mutate({ orderId: order.id, decision: "confirmed", note: paymentNote(order.id) })}>Confirm platform service</button></div></article>)}</div>}<p className="ops-guidance">Confirm only after independently matching the provider evidence to the AHC service order. This record grants or refuses a platform service; it is not a rent-payment or escrow function.</p></section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">03</span><h3><Landmark size={18} /> Cash-flow audit</h3></div><div className="ops-status-strip"><span>Confirmed manual payments</span><b>Payment references remain subject to evidence reconciliation.</b></div><div className="admin-metric-grid"><article><span>Total confirmed revenue</span><b>{formatXaf(cashFlow.data?.confirmedRevenueXaf ?? 0)}</b></article><article><span>Verification revenue</span><b>{formatXaf(cashFlow.data?.physicalVerificationRevenueXaf ?? 0)}</b></article><article><span>Field Moderator accrued</span><b>{formatXaf(cashFlow.data?.fieldModeratorCommissionAccruedXaf ?? 0)}</b></article><article><span>AHC verification share</span><b>{formatXaf(cashFlow.data?.platformCommissionAccruedXaf ?? 0)}</b></article></div><p className="ops-guidance">This is an operational record, not a bank settlement tool. Keep provider receipts and Field Moderator payouts matched to their underlying payment and verification records.</p></section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">03</span><h3><Banknote size={18} /> Verification commission ledger</h3><span className="ops-count">{commissionLedger.data?.length ?? 0}</span></div><div className="ops-status-strip"><span>Evidence-gated payout</span><b>Every Field Moderator allocation stays held until an Admin reviews the saved proof.</b></div>{commissionLedger.isLoading ? <p>Loading commission ledger…</p> : !commissionLedger.data?.length ? <p className="muted">No passed field-verification allocation has been recorded yet.</p> : <div className="commission-ledger">{commissionLedger.data.map(entry => <article key={entry.id}><div><b>Verification #{entry.verificationOrderId} · listing {entry.listingId}</b><span>{entry.moderatorName ?? `Moderator #${entry.moderatorUserId}`} · recorded {new Date(entry.createdAt).toLocaleString()}</span>{entry.evidenceReviewedAt && <small>Evidence reviewed {new Date(entry.evidenceReviewedAt).toLocaleString()}: {entry.evidenceReviewNote}</small>}</div><div><span>Gross</span><b>{formatXaf(entry.grossAmountXaf)}</b></div><div><span>Field Moderator</span><b>{formatXaf(entry.fieldModeratorAmountXaf)} · {(entry.fieldModeratorShareBps / 100).toFixed(0)}%</b></div><div><span>AHC</span><b>{formatXaf(entry.platformAmountXaf)}</b></div>{entry.status === "held" ? <div className="admin-commission-approval"><textarea value={commissionReviewNotes[entry.id] ?? ""} onChange={event => setCommissionReviewNotes(current => ({ ...current, [entry.id]: event.target.value }))} placeholder="Evidence review note: photo-to-listing match, exterior check, and payout decision" /><button className="button-secondary" disabled={approveHeldCommission.isPending || (commissionReviewNotes[entry.id] ?? "").trim().length < 12} onClick={() => approveHeldCommission.mutate({ commissionId: entry.id, evidenceReviewNote: commissionReviewNotes[entry.id] ?? "" })}>{approveHeldCommission.isPending ? <><Loader2 size={15} className="animate-spin" /> Reviewing…</> : "Approve as payable"}</button></div> : <em>{entry.status}</em>}</article>)}</div>}<p className="ops-guidance">Do not make, promise, or record a payout while an allocation is held. Review the required exterior and interior proof against the listing, enter an evidence-review note, then use the approval action. Payout reconciliation remains a separate manual finance record.</p></section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">04</span><h3><BadgeCheck size={18} /> Independent second-visit audits</h3><span className="ops-count">{verificationAudits.data?.length ?? 0}</span></div><div className="ops-status-strip"><span>Random quality control</span><b>Selected visits need a different Field Moderator’s evidence before the original commission can be approved.</b></div>{verificationAudits.isLoading ? <p>Loading independent audits…</p> : !verificationAudits.data?.length ? <p className="muted">No random second-visit audits have been selected.</p> : <div className="commission-ledger">{verificationAudits.data.map(audit => <article key={audit.id}><div><b>{audit.title} · audit #{audit.id}</b><span>Listing {audit.listingId} · first visitor #{audit.primaryModeratorUserId}{audit.auditorUserId ? ` · independent visitor #${audit.auditorUserId}` : " · unclaimed"}</span><small>Status: {audit.status.replaceAll("_", " ")}{audit.listingMatch ? ` · ${audit.listingMatch.replaceAll("_", " ")}` : ""}</small>{audit.observation && <small>{audit.observation}</small>}{audit.exteriorProofUrl && <a className="text-button" href={audit.exteriorProofUrl} target="_blank" rel="noreferrer">Open independent exterior proof</a>} {audit.supportingProofUrl && <a className="text-button" href={audit.supportingProofUrl} target="_blank" rel="noreferrer">Open independent supporting proof</a>}</div><em>{audit.status === "confirmed" ? "Payout gate cleared — still requires Admin review" : "Payout remains held"}</em></article>)}</div>}<p className="ops-guidance">Do not treat a clustered report or a selected audit as automatic proof of misconduct. Where the independent visit disputes the original outcome, keep the listing and commission on hold, review both proof packages, contact the parties, and document the final administrative decision.</p></section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">05</span><h3><Flag size={18} /> Seeker trust reports</h3><span className="ops-count">{trustReports.data?.length ?? 0}</span></div><div className="ops-status-strip"><span>Private escalation queue</span><b>Three distinct inaccurate-cost or unavailable-listing reports automatically place a listing and Agent access on safety hold.</b></div>{trustReports.isLoading ? <p>Loading seeker reports…</p> : !trustReports.data?.length ? <p className="muted">No seeker trust reports have been filed.</p> : <div className="commission-ledger">{trustReports.data.map(report => <article key={report.id}><div><b>{report.listingTitle} · {report.reason.replaceAll("_", " ")}</b><span>Listing {report.listingId} · reporter account #{report.reporterUserId ?? "deleted"} · {new Date(report.filedAt).toLocaleString()}</span><small>{report.note}</small>{(report.integritySignals.recentAccount || report.integritySignals.clusteredNetwork) && <small><b>Fair-review signal:</b> {report.integritySignals.recentAccount ? `account created ${report.reporterAccountAgeDays} day(s) ago` : ""}{report.integritySignals.recentAccount && report.integritySignals.clusteredNetwork ? " · " : ""}{report.integritySignals.clusteredNetwork ? `${report.networkPatternCount} reports share a keyed network pattern` : ""}. This is not proof; investigate before any permanent sanction.</small>}</div><em>{report.status} · listing {report.listingStatus}</em>{report.listingStatus === "suspended" && <div className="admin-commission-approval"><textarea value={safetyReleaseReasons[report.listingId] ?? ""} onChange={event => setSafetyReleaseReasons(current => ({ ...current, [report.listingId]: event.target.value }))} placeholder="Required documented finding before releasing this safety hold" /><button className="button-secondary" disabled={releaseSafetyHold.isPending || (safetyReleaseReasons[report.listingId] ?? "").trim().length < 12} onClick={() => releaseSafetyHold.mutate({ listingId: report.listingId, reason: safetyReleaseReasons[report.listingId] ?? "" })}>Release safety hold</button></div>}</article>)}</div>}<p className="ops-guidance">A safety hold is an investigation trigger, not proof of misconduct. Before releasing it, compare listing costs and availability, check account-age and keyed network-pattern signals, contact both parties, and record the reason. Releasing resolves the open reports, republishes the listing with a fresh reconfirmation window, and sends only a data-minimal owner alert.</p></section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">06</span><h3><MessageCircle size={18} /> Owner-only WhatsApp operational alerts</h3><span className="ops-count">{ownerAlerts.data?.length ?? 0}</span></div><div className="ops-status-strip"><span>{ownerAlertProvider.data?.active ? "Meta delivery active" : "Provider or dispatch paused"}</span><b>Only an event label, non-sensitive reference, and Admin dashboard link are sent. Rent, deposits, tenancy money, private evidence, exact addresses, and payment references are excluded.</b></div><div className="admin-metric-grid"><article><span>Provider</span><b>{ownerAlertProvider.data?.provider ?? "Checking…"}</b></article><article><span>Owner recipient</span><b>{ownerAlertProvider.data?.ownerPhoneMasked ?? "Not configured"}</b></article><article><span>Utility template</span><b>{ownerAlertProvider.data?.templateName ?? "Not configured"}</b></article><article><span>Dispatch status</span><b>{ownerAlertProvider.data?.enabled ? "Enabled" : "Paused"}</b></article></div>{draft && <label className="ops-guidance"><input type="checkbox" checked={draft.ownerAlertsEnabled} onChange={event => { const next = { ...draft, ownerAlertsEnabled: event.target.checked }; setDraft(next); updateSettings.mutate(next); }} disabled={updateSettings.isPending} /> Enable automatic owner alerts for future high-priority events.</label>}<div className="ops-actions"><button className="button-secondary" disabled={sendOwnerAlertTest.isPending} onClick={() => sendOwnerAlertTest.mutate()}>{sendOwnerAlertTest.isPending ? <><Loader2 size={15} className="animate-spin" /> Sending test…</> : "Send test owner alert"}</button></div><p className="ops-guidance">Phone number and provider secrets cannot be edited here. Configure the protected WhatsApp credentials in project Secrets, then create and approve the specified utility template before attempting live delivery. When unconfigured, alerts remain queued rather than sending a fallback message.</p>{ownerAlerts.isLoading ? <p>Loading alert history…</p> : !ownerAlerts.data?.length ? <p className="muted">No owner alerts have been queued yet.</p> : <div className="commission-ledger">{ownerAlerts.data.map(alert => <article key={alert.id}><div><b>{alert.eventType.replaceAll("_", " ")} · {alert.referenceId}</b><span>Queued {new Date(alert.queuedAt).toLocaleString()} · {alert.provider.replaceAll("_", " ")} · attempt {alert.attemptCount}</span><small>{alert.summary}</small>{alert.failureReason && <small>Delivery note: {alert.failureReason}</small>}</div><em>{alert.status}</em></article>)}</div>}</section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">05</span><h3><MessageCircle size={18} /> WhatsApp lead clicks</h3><span className="ops-count">{leadEvents.data?.reduce((total, event) => total + event.clickCount, 0) ?? 0}</span></div><div className="ops-status-strip"><span>Cumulative outbound contact intent</span><b>One card is shown per listing. Its number increases whenever the tracked WhatsApp route is clicked; AHC records no messages, phone content, location, or claimed conversion.</b></div>{leadEvents.isLoading ? <p>Loading lead clicks…</p> : !leadEvents.data?.length ? <p className="muted">No authenticated WhatsApp contact clicks have been recorded.</p> : <div className="commission-ledger">{leadEvents.data.map(event => <article key={event.listingId}><div><b>{event.listingTitle} · {event.city}</b><span>Listing {event.listingId} · {event.uniqueSeekerCount} distinct signed-in seeker{event.uniqueSeekerCount === 1 ? "" : "s"}</span><small>First tracked {new Date(event.firstClickedAt).toLocaleString()} · most recent {new Date(event.lastClickedAt).toLocaleString()} · {event.channel}</small></div><em>{event.clickCount} WhatsApp click{event.clickCount === 1 ? "" : "s"}</em></article>)}</div>}<p className="ops-guidance">A click count confirms only that the tracked AHC route redirected a signed-in seeker to WhatsApp. It cannot prove a viewing, payment, tenancy, or message outcome; staff must never describe it as a conversion.</p></section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">06</span><h3><UsersRound size={18} /> Account protection</h3><span className="ops-count">{users.data?.length ?? 0}</span></div><div className="ops-status-strip"><span>Access controls</span><b>Every ban or reinstatement is immutably recorded with its rationale.</b></div><div className="admin-user-list">{users.isLoading ? <p>Loading account records…</p> : users.data?.map(account => <article key={account.id} className="admin-user-row"><div><b>{account.name ?? "Unnamed account"}</b><span>{account.email ?? `Account #${account.id}`} · {account.role}</span>{account.isBanned && <small>Suspended: {account.banReason ?? "No reason recorded"}</small>}</div><div><textarea value={reasons[account.id] ?? ""} onChange={event => setReasons(current => ({ ...current, [account.id]: event.target.value }))} placeholder={account.isBanned ? "Reason for reinstatement" : "Required suspension reason"} /><button className={account.isBanned ? "button-secondary" : "button-secondary danger"} disabled={setBan.isPending || (reasons[account.id] ?? "").trim().length < 8 || account.role === "admin"} onClick={() => setBan.mutate({ userId: account.id, isBanned: !account.isBanned, reason: reasons[account.id] ?? "" })}>{account.isBanned ? "Reinstate account" : <><ShieldAlert size={15} /> Suspend account</>}</button></div></article>)}</div></section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">07</span><h3><UsersRound size={18} /> Trusted staff authority</h3></div><div className="ops-status-strip"><span>Private role assignment</span><b>Accounts must exist first. Registration never creates a Moderator or Admin.</b></div><p className="ops-guidance">Use this restricted screen to assign a trusted existing AHC account as a Field Moderator or additional Admin. Every change is recorded in the immutable admin audit trail. Do not share the `/admin` address with public users.</p><div className="admin-user-list">{users.isLoading ? <p>Loading accounts…</p> : users.data?.map(account => { const selectedRole = roleDrafts[account.id] ?? account.role; const isSelf = account.id === user?.id; return <article key={`role-${account.id}`} className="admin-user-row"><div><b>{account.name ?? "Unnamed account"}</b><span>{account.email ?? `Account #${account.id}`} · current role: {account.role}</span></div><div className="role-assignment-controls"><select aria-label={`Role for ${account.name ?? account.id}`} value={selectedRole} disabled={isSelf || setRole.isPending} onChange={event => setRoleDrafts(current => ({ ...current, [account.id]: event.target.value as "user" | "moderator" | "admin" }))}><option value="user">Seeker / Agent</option><option value="moderator">Field Moderator</option><option value="admin">Admin</option></select><button className="button-secondary" disabled={isSelf || setRole.isPending || selectedRole === account.role} onClick={() => setRole.mutate({ userId: account.id, role: selectedRole })}>{isSelf ? "Your own role is protected" : setRole.isPending ? "Saving…" : "Save trusted role"}</button></div></article>; })}</div></section>
    <footer className="admin-role-boundary"><Banknote size={16} /><p><b>Authority boundary.</b> Admin manages settings, staff authority, bans, cash-flow and audit. Field Moderators collect only visit evidence, can claim assigned field work, and earn the recorded commission after a passed verification.</p></footer>
    {receipt.data && <OfficialServiceReceipt receipt={receipt.data} onClose={() => setReceiptOrderId(null)} />}
  </section>;
}
