import { useEffect, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Banknote, Landmark, ShieldAlert, SlidersHorizontal, UsersRound, X } from "lucide-react";
import { toast } from "sonner";
import "./launch-refinements.css";

const formatXaf = (value: number) => `${new Intl.NumberFormat("en-US").format(value)} XAF`;
type SettingsDraft = { agentAccessFeeXaf: number; listingPassFeeXaf: number; featuredPinFeeXaf: number; physicalVerificationFeeXaf: number; fieldModeratorShareBps: number };

export default function AdminPortal({ onClose }: { onClose: () => void }) {
  const { user, isAuthenticated } = useAuth();
  const enabled = isAuthenticated && user?.role === "admin";
  const utils = trpc.useUtils();
  const settings = trpc.admin.settings.useQuery(undefined, { enabled });
  const users = trpc.admin.users.useQuery(undefined, { enabled });
  const cashFlow = trpc.admin.cashFlowAudit.useQuery(undefined, { enabled });
  const commissionLedger = trpc.admin.commissionLedger.useQuery(undefined, { enabled });
  const [draft, setDraft] = useState<SettingsDraft | null>(null);
  const [reasons, setReasons] = useState<Record<number, string>>({});
  const [roleDrafts, setRoleDrafts] = useState<Record<number, "user" | "moderator" | "admin">>({});
  useEffect(() => {
    if (settings.data) setDraft({ agentAccessFeeXaf: settings.data.agentAccessFeeXaf, listingPassFeeXaf: settings.data.listingPassFeeXaf, featuredPinFeeXaf: settings.data.featuredPinFeeXaf, physicalVerificationFeeXaf: settings.data.physicalVerificationFeeXaf, fieldModeratorShareBps: settings.data.fieldModeratorShareBps });
  }, [settings.data]);
  const updateSettings = trpc.admin.updateSettings.useMutation({ onSuccess: () => { utils.admin.settings.invalidate(); toast.success("Commercial settings saved and audited."); } });
  const setBan = trpc.admin.setUserBan.useMutation({ onSuccess: () => { utils.admin.users.invalidate(); toast.success("Account access record updated."); } });
  const setRole = trpc.admin.setUserRole.useMutation({ onSuccess: () => { utils.admin.users.invalidate(); toast.success("Trusted role assignment saved and audited."); }, onError: error => toast.error(error.message) });
  const setNumber = (key: keyof SettingsDraft, raw: string) => setDraft(current => current ? { ...current, [key]: Number(raw) || 0 } : current);

  if (!enabled) return <section className="agent-drawer admin-drawer"><button className="drawer-close" onClick={onClose}><X size={19} /></button><span className="section-overline">AHC / Admin</span><h2>Platform management is restricted.</h2><p>Only the designated AHC administrator can manage platform fees, cash-flow records, and account access. Field Moderators use <a href="/operations">Operations</a> for on-ground review work.</p></section>;

  return <section className="agent-drawer scroll operations-drawer admin-drawer"><button className="drawer-close" onClick={onClose}><X size={19} /></button><header className="ops-atlas-header admin-atlas-header"><div className="ops-brand-lockup"><span className="ops-brand-emblem"><span /><span /><span /></span><span>Affordable Housing<b>Cameroon / platform admin</b></span></div><span className="section-overline">Admin route / restricted governance</span><h2>Manage trust, access, and the cash record.</h2><p>Field Moderators verify properties on the ground. Administrators set commercial rules, protect the network, and audit all paid activity.</p><span className="ops-trust-pulse"><i /> Admin audit on</span></header>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">01</span><h3><SlidersHorizontal size={18} /> Commercial settings</h3></div><div className="ops-status-strip"><span>Governed pricing</span><b>Changes apply to newly created payment orders only.</b></div>{!draft ? <p>Loading commercial settings…</p> : <form className="admin-settings-grid" onSubmit={event => { event.preventDefault(); updateSettings.mutate(draft); }}><label>Agent Access <span>XAF / 30 days</span><input type="number" min="0" value={draft.agentAccessFeeXaf} onChange={event => setNumber("agentAccessFeeXaf", event.target.value)} /></label><label>Listing Pass <span>XAF / 90 days</span><input type="number" min="0" value={draft.listingPassFeeXaf} onChange={event => setNumber("listingPassFeeXaf", event.target.value)} /></label><label>Featured Landmark Pin <span>XAF / 14 days</span><input type="number" min="0" value={draft.featuredPinFeeXaf} onChange={event => setNumber("featuredPinFeeXaf", event.target.value)} /></label><label>Physical verification <span>XAF / badge cycle</span><input type="number" min="0" value={draft.physicalVerificationFeeXaf} onChange={event => setNumber("physicalVerificationFeeXaf", event.target.value)} /></label><label>Field Moderator share <span>basis points / 10,000</span><input type="number" min="0" max="10000" value={draft.fieldModeratorShareBps} onChange={event => setNumber("fieldModeratorShareBps", event.target.value)} /></label><div className="admin-settings-callout"><b>{(draft.fieldModeratorShareBps / 100).toFixed(0)}% Field Moderator / {((10_000 - draft.fieldModeratorShareBps) / 100).toFixed(0)}% AHC</b><span>Recorded when a paid field verification passes.</span></div><button className="button-primary" type="submit" disabled={updateSettings.isPending}>Save governed settings</button></form>}</section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">02</span><h3><Landmark size={18} /> Cash-flow audit</h3></div><div className="ops-status-strip"><span>Confirmed manual payments</span><b>Payment references remain subject to evidence reconciliation.</b></div><div className="admin-metric-grid"><article><span>Total confirmed revenue</span><b>{formatXaf(cashFlow.data?.confirmedRevenueXaf ?? 0)}</b></article><article><span>Verification revenue</span><b>{formatXaf(cashFlow.data?.physicalVerificationRevenueXaf ?? 0)}</b></article><article><span>Field Moderator accrued</span><b>{formatXaf(cashFlow.data?.fieldModeratorCommissionAccruedXaf ?? 0)}</b></article><article><span>AHC verification share</span><b>{formatXaf(cashFlow.data?.platformCommissionAccruedXaf ?? 0)}</b></article></div><p className="ops-guidance">This is an operational record, not a bank settlement tool. Keep provider receipts and Field Moderator payouts matched to their underlying payment and verification records.</p></section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">03</span><h3><Banknote size={18} /> Verification commission ledger</h3><span className="ops-count">{commissionLedger.data?.length ?? 0}</span></div><div className="ops-status-strip"><span>Immutable allocations</span><b>Each row is created only after a Field Moderator passes a paid visit.</b></div>{commissionLedger.isLoading ? <p>Loading commission ledger…</p> : !commissionLedger.data?.length ? <p className="muted">No passed field-verification allocation has been recorded yet.</p> : <div className="commission-ledger">{commissionLedger.data.map(entry => <article key={entry.id}><div><b>Verification #{entry.verificationOrderId} · listing {entry.listingId}</b><span>{entry.moderatorName ?? `Moderator #${entry.moderatorUserId}`} · recorded {new Date(entry.createdAt).toLocaleString()}</span></div><div><span>Gross</span><b>{formatXaf(entry.grossAmountXaf)}</b></div><div><span>Field Moderator</span><b>{formatXaf(entry.fieldModeratorAmountXaf)} · {(entry.fieldModeratorShareBps / 100).toFixed(0)}%</b></div><div><span>AHC</span><b>{formatXaf(entry.platformAmountXaf)}</b></div><em>{entry.status}</em></article>)}</div>}</section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">04</span><h3><UsersRound size={18} /> Account protection</h3><span className="ops-count">{users.data?.length ?? 0}</span></div><div className="ops-status-strip"><span>Access controls</span><b>Every ban or reinstatement is immutably recorded with its rationale.</b></div><div className="admin-user-list">{users.isLoading ? <p>Loading account records…</p> : users.data?.map(account => <article key={account.id} className="admin-user-row"><div><b>{account.name ?? "Unnamed account"}</b><span>{account.email ?? `Account #${account.id}`} · {account.role}</span>{account.isBanned && <small>Suspended: {account.banReason ?? "No reason recorded"}</small>}</div><div><textarea value={reasons[account.id] ?? ""} onChange={event => setReasons(current => ({ ...current, [account.id]: event.target.value }))} placeholder={account.isBanned ? "Reason for reinstatement" : "Required suspension reason"} /><button className={account.isBanned ? "button-secondary" : "button-secondary danger"} disabled={setBan.isPending || (reasons[account.id] ?? "").trim().length < 8 || account.role === "admin"} onClick={() => setBan.mutate({ userId: account.id, isBanned: !account.isBanned, reason: reasons[account.id] ?? "" })}>{account.isBanned ? "Reinstate account" : <><ShieldAlert size={15} /> Suspend account</>}</button></div></article>)}</div></section>
    <section className="ops-section"><div className="ops-route-heading"><span className="ops-route-number">05</span><h3><UsersRound size={18} /> Trusted staff authority</h3></div><div className="ops-status-strip"><span>Private role assignment</span><b>Accounts must exist first. Registration never creates a Moderator or Admin.</b></div><p className="ops-guidance">Use this restricted screen to assign a trusted existing AHC account as a Field Moderator or additional Admin. Every change is recorded in the immutable admin audit trail. Do not share the `/admin` address with public users.</p><div className="admin-user-list">{users.isLoading ? <p>Loading accounts…</p> : users.data?.map(account => { const selectedRole = roleDrafts[account.id] ?? account.role; const isSelf = account.id === user?.id; return <article key={`role-${account.id}`} className="admin-user-row"><div><b>{account.name ?? "Unnamed account"}</b><span>{account.email ?? `Account #${account.id}`} · current role: {account.role}</span></div><div className="role-assignment-controls"><select aria-label={`Role for ${account.name ?? account.id}`} value={selectedRole} disabled={isSelf || setRole.isPending} onChange={event => setRoleDrafts(current => ({ ...current, [account.id]: event.target.value as "user" | "moderator" | "admin" }))}><option value="user">Seeker / Agent</option><option value="moderator">Field Moderator</option><option value="admin">Admin</option></select><button className="button-secondary" disabled={isSelf || setRole.isPending || selectedRole === account.role} onClick={() => setRole.mutate({ userId: account.id, role: selectedRole })}>{isSelf ? "Your own role is protected" : setRole.isPending ? "Saving…" : "Save trusted role"}</button></div></article>; })}</div></section>
    <footer className="admin-role-boundary"><Banknote size={16} /><p><b>Authority boundary.</b> Admin manages settings, staff authority, bans, cash-flow and audit. Field Moderators collect only visit evidence, can claim assigned field work, and earn the recorded commission after a passed verification.</p></footer>
  </section>;
}
