import { useState } from "react";
import { CalendarCheck2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { agentText } from "@/lib/agentWorkspaceLocale";
import type { PublicLanguage } from "@/lib/marketplaceLocale";
import "./agent-viewing-concierge.css";

export function AgentViewingConcierge({ language }: { language: PublicLanguage }) {
  const utils = trpc.useUtils();
  const copy = (key: Parameters<typeof agentText>[1]) => agentText(language, key);
  const appointments = trpc.agent.viewingAppointments.list.useQuery();
  const [notes, setNotes] = useState<Record<number, string>>({});
  const refresh = () => utils.agent.viewingAppointments.list.invalidate();
  const respond = trpc.agent.viewingAppointments.respond.useMutation({ onSuccess: result => { refresh(); toast.success(result.status === "confirmed" ? copy("viewingConfirmed") : copy("viewingDeclined")); }, onError: error => toast.error(copy("unableUpdate"), { description: error.message }) });
  const cancel = trpc.agent.viewingAppointments.cancel.useMutation({ onSuccess: () => { refresh(); toast.success(copy("viewingCancelled")); }, onError: error => toast.error(copy("unableCancel"), { description: error.message }) });
  const outcome = trpc.agent.viewingAppointments.recordOutcome.useMutation({ onSuccess: result => { refresh(); toast.success(result.status === "completed" ? copy("completed") : copy("noShow")); }, onError: error => toast.error(copy("unableOutcome"), { description: error.message }) });

  return <section className="agent-section appointment-concierge"><h3><CalendarCheck2 size={17} /> {copy("concierge")}</h3><p>{copy("conciergeBody")}</p>{appointments.isLoading ? <p className="muted">{copy("loadingRequests")}</p> : appointments.data?.length ? <div className="agent-appointment-list">{appointments.data.map(appointment => { const note = notes[appointment.id] ?? ""; const canRecordOutcome = appointment.status === "confirmed" && new Date(appointment.requestedStart).getTime() <= Date.now(); return <article key={appointment.id}><div className="appointment-summary"><span className="section-overline">{appointment.status.replaceAll("_", " ")}</span><b>{appointment.listingTitle}</b><span>{appointment.seekerName} · {new Date(appointment.requestedStart).toLocaleString(language === "fr" ? "fr-FR" : "en-GB", { weekday: "short", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}</span>{appointment.seekerNote && <small>{copy("seekerNote")}: {appointment.seekerNote}</small>}{appointment.seekerContact ? <strong>{appointment.contactPreference === "whatsapp" ? "WhatsApp" : "Phone"}: {appointment.seekerContact}</strong> : <small>{copy("privateUntilConfirm")}</small>}</div>{appointment.status === "requested" && <div className="appointment-actions"><textarea value={note} maxLength={500} onChange={event => setNotes(current => ({ ...current, [appointment.id]: event.target.value }))} placeholder={copy("confirmationNote")} /><div><button className="button-secondary" disabled={respond.isPending} onClick={() => respond.mutate({ appointmentId: appointment.id, decision: "confirmed", note: note || undefined })}>{copy("confirm")}</button><button className="text-button" disabled={respond.isPending || note.trim().length < 4} onClick={() => respond.mutate({ appointmentId: appointment.id, decision: "declined", note })}>{copy("decline")}</button></div></div>}{appointment.status === "confirmed" && <div className="appointment-actions"><button className="text-button" disabled={cancel.isPending} onClick={() => cancel.mutate({ appointmentId: appointment.id, note: copy("agentCancelled") })}>{copy("cancel")}</button>{canRecordOutcome && <div><button className="button-secondary" disabled={outcome.isPending} onClick={() => outcome.mutate({ appointmentId: appointment.id, outcome: "completed", note: note || undefined })}>{copy("markComplete")}</button><button className="text-button" disabled={outcome.isPending} onClick={() => outcome.mutate({ appointmentId: appointment.id, outcome: "no_show", note: note || undefined })}>{copy("recordNoShow")}</button></div>}</div>}</article>; })}</div> : <p className="muted">{copy("noRequests")}</p>}</section>;
}
