import { useState } from "react";
import { CalendarCheck2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import "./agent-viewing-concierge.css";

export function AgentViewingConcierge() {
  const utils = trpc.useUtils();
  const appointments = trpc.agent.viewingAppointments.list.useQuery();
  const [notes, setNotes] = useState<Record<number, string>>({});
  const refresh = () => utils.agent.viewingAppointments.list.invalidate();
  const respond = trpc.agent.viewingAppointments.respond.useMutation({ onSuccess: result => { refresh(); toast.success(result.status === "confirmed" ? "Viewing confirmed" : "Viewing declined"); }, onError: error => toast.error("Unable to update viewing", { description: error.message }) });
  const cancel = trpc.agent.viewingAppointments.cancel.useMutation({ onSuccess: () => { refresh(); toast.success("Viewing appointment cancelled"); }, onError: error => toast.error("Unable to cancel viewing", { description: error.message }) });
  const outcome = trpc.agent.viewingAppointments.recordOutcome.useMutation({ onSuccess: result => { refresh(); toast.success(result.status === "completed" ? "Viewing marked complete" : "No-show recorded"); }, onError: error => toast.error("Unable to record outcome", { description: error.message }) });

  return <section className="agent-section appointment-concierge"><h3><CalendarCheck2 size={17} /> Viewing concierge</h3><p>Review requests for physically verified homes. AHC keeps contact details and compound access private until you confirm the time window.</p>{appointments.isLoading ? <p className="muted">Loading viewing requests…</p> : appointments.data?.length ? <div className="agent-appointment-list">{appointments.data.map(appointment => { const note = notes[appointment.id] ?? ""; const canRecordOutcome = appointment.status === "confirmed" && new Date(appointment.requestedStart).getTime() <= Date.now(); return <article key={appointment.id}><div className="appointment-summary"><span className="section-overline">{appointment.status.replaceAll("_", " ")}</span><b>{appointment.listingTitle}</b><span>{appointment.seekerName} · {new Date(appointment.requestedStart).toLocaleString("en-GB", { weekday: "short", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}</span>{appointment.seekerNote && <small>Seeker note: {appointment.seekerNote}</small>}{appointment.seekerContact ? <strong>{appointment.contactPreference === "whatsapp" ? "WhatsApp" : "Phone"}: {appointment.seekerContact}</strong> : <small>Contact stays private until you confirm.</small>}</div>{appointment.status === "requested" && <div className="appointment-actions"><textarea value={note} maxLength={500} onChange={event => setNotes(current => ({ ...current, [appointment.id]: event.target.value }))} placeholder="Optional confirmation note; required if declining" /><div><button className="button-secondary" disabled={respond.isPending} onClick={() => respond.mutate({ appointmentId: appointment.id, decision: "confirmed", note: note || undefined })}>Confirm</button><button className="text-button" disabled={respond.isPending || note.trim().length < 4} onClick={() => respond.mutate({ appointmentId: appointment.id, decision: "declined", note })}>Decline</button></div></div>}{appointment.status === "confirmed" && <div className="appointment-actions"><button className="text-button" disabled={cancel.isPending} onClick={() => cancel.mutate({ appointmentId: appointment.id, note: "Agent cancelled this viewing appointment." })}>Cancel</button>{canRecordOutcome && <div><button className="button-secondary" disabled={outcome.isPending} onClick={() => outcome.mutate({ appointmentId: appointment.id, outcome: "completed", note: note || undefined })}>Mark completed</button><button className="text-button" disabled={outcome.isPending} onClick={() => outcome.mutate({ appointmentId: appointment.id, outcome: "no_show", note: note || undefined })}>Record no-show</button></div>}</div>}</article>; })}</div> : <p className="muted">No viewing requests yet. Requests open only for live, physically verified listings.</p>}</section>;
}
